package frc.robot.SWERVE;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.OptionalDouble;
import java.util.function.Supplier;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.math.geometry.Pose2d;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.SWERVE.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Always treat the physical front of the robot as forward on boot */
    private static final Rotation2d kOperatorPerspectiveForward = Rotation2d.kZero;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    private final StructPublisher<Pose2d> posePublisher =
        NetworkTableInstance.getDefault()
            .getStructTopic("DriveState/Pose", Pose2d.struct)
            .publish();

    /* =========================
     * PathPlanner helpers
     * ========================= */
    private final SwerveRequest.RobotCentric m_pathplannerRobotCentric =
        new SwerveRequest.RobotCentric()
            .withDriveRequestType(DriveRequestType.Velocity);

    // If present, this replaces the omega from PathPlanner (rad/s)
    private OptionalDouble m_omegaOverrideRadPerSec = OptionalDouble.empty();

    public void setOmegaOverride(double omegaRadPerSec) {
        m_omegaOverrideRadPerSec = OptionalDouble.of(omegaRadPerSec);
    }

    public void clearOmegaOverride() {
        m_omegaOverrideRadPerSec = OptionalDouble.empty();
    }

    /** Used by AutoBuilder: current robot-relative speeds */
    public ChassisSpeeds getRobotRelativeSpeeds() {
        return this.getState().Speeds;
    }

    /**
     * Used by AutoBuilder: drive robot-relative speeds.
     * If omega override is set, it will replace speeds.omegaRadiansPerSecond.
     */
    public void driveRobotRelative(ChassisSpeeds speeds) {
        double omega = m_omegaOverrideRadPerSec.isPresent()
            ? m_omegaOverrideRadPerSec.getAsDouble()
            : speeds.omegaRadiansPerSecond;

        this.setControl(
            m_pathplannerRobotCentric
                .withVelocityX(speeds.vxMetersPerSecond)
                .withVelocityY(speeds.vyMetersPerSecond)
                .withRotationalRate(omega)
        );
    }

    /**
     * Used by AutoBuilder: reset the robot pose to a known pose at the start of autos.
     * If your Phoenix version uses a different method name, change this ONE line.
     */
    @Override
    public void resetPose(Pose2d pose) {
        super.resetPose(pose); // resets X, Y, and heading
    }

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    private void publishOdometryToDashboard() {
        Pose2d pose = this.getState().Pose;

        SmartDashboard.putNumber("Odo/X_m", pose.getX());
        SmartDashboard.putNumber("Odo/Y_m", pose.getY());
        SmartDashboard.putNumber("Odo/Heading_deg", pose.getRotation().getDegrees());

        SmartDashboard.putNumber("Odo/Speed_mps", this.getState().Speeds.vxMetersPerSecond);
        SmartDashboard.putNumber("Odo/Omega_radps", this.getState().Speeds.omegaRadiansPerSecond);
    }

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            Volts.of(Math.PI / 6).per(Second),
            Volts.of(Math.PI),
            null,
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
public void periodic() {
    if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
        DriverStation.getAlliance().ifPresent(allianceColor -> {
            setOperatorPerspectiveForward(
                allianceColor == DriverStation.Alliance.Red
                    ? Rotation2d.k180deg
                    : Rotation2d.kZero
            );
            m_hasAppliedOperatorPerspective = true;
        });
    }

    Pose2d pose = this.getState().Pose;
    posePublisher.set(pose);

    SmartDashboard.putNumber("AScope/X", pose.getX());
    SmartDashboard.putNumber("AScope/Y", pose.getY());
    SmartDashboard.putNumber("AScopeHeadingDeg", this.getState().Pose.getRotation().getDegrees());
    SmartDashboard.putNumber("AScopeOmegaRadPerSec", this.getState().Speeds.omegaRadiansPerSecond);
    SmartDashboard.putNumber("AScope/HeadingDeg", pose.getRotation().getDegrees());
    SmartDashboard.putNumber("PoseHeadingDeg", this.getState().Pose.getRotation().getDegrees());
    SmartDashboard.putNumber("OmegaRadPerSec", this.getState().Speeds.omegaRadiansPerSecond);
    SmartDashboard.putNumber("RawPigeonYawDeg", this.getPigeon2().getYaw().getValueAsDouble());
}

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }
}